version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 274201610284.dkr.ecr.us-west-2.amazonaws.com
      - IMAGE_NAME=eureka-server
      - IMAGE_URI=274201610284.dkr.ecr.us-west-2.amazonaws.com/2048947_images:processPension
      - CONTAINER_NAME=eureka-server
  build:
    commands:
      - echo Build started on 'date'
      - echo $IMAGE_NAME
      - echo $CONTAINER_NAME
      - cd PensionManagementSystem/eureka-server
      - mvn compile
      - mvn package
      - echo Building the Docker image...
      - docker build -t $IMAGE_NAME .
  post_build:
    commands:
      - echo Build completed on 'date'
      - echo $(docker images)
      - docker tag $IMAGE_NAME $IMAGE_URI
      - echo Pushin the Docker image...
      - docker push $IMAGE_URI
      - echo push completed
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $IMAGE_URI > taskdefinition.json



artifacts:
  files: PensionManagementSystem/eureka-server/taskdefinition.json